frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

publicaciones:
    resource: "@PublicacionesBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"